### ISSUE TITLE
BUG: First page load always errors when the users token expires

### ISSUE THREAD

**Issue by Zimbardoex** [op-analytics/Media-Analytics#356]
**Describe the bug**
The first time the frequency page is loaded, it give an "Cannot read property errors of undefined" error.

**To Reproduce**
1. docker-compose up
2. Go to localhost:3000 with an expired user token

**Expected behavior**
There should not be an error, and the user should be logged out succesfully

**Comment by NICHTJ3** [comment]
This is due to the backend not returning a response. We might need to have a default error message

**Comment by NICHTJ3** [comment]
This also appears to happen if you jwt has expired

**Comment by NICHTJ3** [comment]
This might be resolved in the newest version I will update in the next couple days

**Comment by NICHTJ3** [comment]
Still happens when the JWT is expired but the original issue appears to have been resolved
